const goats = [
  {
    id: 'goat1',
    name: 'billy',
    disposition: 'rude',
    imageUrl: 'https://upload.wikimedia.org/wikipedia/commons/thumb/5/55/A_white_irish_goat.jpg/220px-A_white_irish_goat.jpg',
    fullness: 67,
    favPose: 'down dog',
    isFainting: true,
    color: 'brown',
  },
  {
    id: 'goat2',
    name: 'phil',
    disposition: 'calm',
    imageUrl: 'https://www.telegraph.co.uk/content/dam/pets/2016/08/11/103675361_jack-the-goat-PETS_trans_NvBQzQNjv4BqZgEkZX3M936N5BQK4Va8RWtT0gK_6EfZT336f62EI5U.jpg?imwidth=450',
    fullness: 45,
    favPose: 'lotus',
    isFainting: true,
    color: 'red',
  },
  {
    id: 'goat3',
    name: 'bob',
    disposition: 'friendly',
    imageUrl: 'https://ichef.bbci.co.uk/news/660/cpsprodpb/12E1C/production/_103204377_mediaitem103204376.jpg',
    fullness: 1,
    favPose: 'savasana',
    isFainting: false,
    color: 'green',
  },
  {
    id: 'goat4',
    name: 'fin',
    disposition: 'sneaky',
    imageUrl: 'https://img.purch.com/rc/300x200/aHR0cDovL3d3dy5saXZlc2NpZW5jZS5jb20vaW1hZ2VzL2kvMDAwLzA2NC85NTUvb3JpZ2luYWwvZ29hdF9waWMuanBn',
    fullness: 89,
    favPose: 'tree',
    isFainting: false,
    color: 'brown',
  },
  {
    id: 'goat5',
    name: 'john',
    disposition: 'protective',
    imageUrl: 'https://www.calacademy.org/sites/default/files/styles/manual_crop_standard_960x540/public/190418_goat_1200x900.jpg?itok=pEVC9cTh&c=abc0317824bdb6e4e86588a62f24d720',
    fullness: 35,
    favPose: 'boat',
    isFainting: true,
    color: 'red',
  },
];

export default { goats };
